export const exercises = [
  {
    id: 1,
    title: "حرکات پا",
    slug: "squat",
    image: "/images/SportEdu/edu1.jpg",
    images: [
      "/images/SportEdu/edu1.jpg",
      "/images/SportEdu/edu1-2.jpg",
      "/images/SportEdu/edu1-3.jpg",
    ],
    level: "متوسط",
    equipment: ["هالتر (اختیاری)"],
    muscles: {
      primary: ["ران", "باسن"],
      secondary: ["core", "ساق پا"],
    },
    description:
      "اسکات یکی از مهم‌ترین و پایه‌ای‌ترین حرکات بدنسازی است که باعث افزایش قدرت، حجم عضلات پایین‌تنه و بهبود تعادل بدن می‌شود.",
    executionSteps: [
      "  پاها را به عرض شانه باز کن ",
      "   کمر صاف و سینه بالا باشد  ",
      " باسن را عقب بده و بنشین  ",
      "تا جایی پایین برو که ران‌ها موازی زمین شوند ",
      "با فشار از پاشنه‌ها به حالت اول برگرد ",
    ],
    tips: [
      "  زانوها به داخل جمع نشوند",
      "نگاه رو به جلو باشد  ",
      "وزن بدن روی پاشنه پاها قرار بگیرد",
    ],
    commonMistakes: [
      "خم شدن بیش از حد کمر",
      "بلند شدن پاشنه‌ها از زمین",
      "قفل کردن زانوها در بالا",
    ],
    benefits: [
      "افزایش قدرت پایین‌تنه",
      "تقویت عضلات مرکزی بدن",
      "افزایش متابولیسم",
    ],
    relatedExercises: ["leg-press", "lunges"],
  },
  {
    id: 2,
    title: "پرس سینه",
    slug: "bench-press",
    image: "/images/SportEdu/edu2.webp",
    images: ["/images/SportEdu/edu1-1.jpg", "/images/SportEdu/edu1-1.jpg"],
    level: "متوسط",
    equipment: ["هالتر", "نیمکت"],
    muscles: {
      primary: ["سینه"],
      secondary: ["سرشانه", "پشت بازو"],
    },
    description:
      "پرس سینه حرکت اصلی برای افزایش حجم و قدرت عضلات سینه است و یکی از حرکات پایه در برنامه‌های بدنسازی محسوب می‌شود.",
    executionSteps: [
      "روی نیمکت دراز بکش",
      "دست‌ها کمی بازتر از عرض شانه",
      "میله را کنترل‌شده پایین بیاور",
      "تا نزدیکی سینه پایین بیاور",
      "با قدرت به بالا پرس کن",
    ],
    tips: [
      "شانه‌ها را به عقب جمع کن",
      "کنترل حرکت را حفظ کن",
      "آرنج‌ها بیش از حد باز نشوند",
    ],
    commonMistakes: [
      "برخورد میله با سینه",
      "قفل کردن آرنج‌ها",
      "برداشتن باسن از نیمکت",
    ],
    benefits: ["افزایش حجم عضلات سینه", "افزایش قدرت بالاتنه"],
    relatedExercises: ["incline-bench-press", "chest-fly"],
  },
  {
    id: 3,
    title: "جلو بازو دمبل",
    slug: "bicep-curl",
    image: "/images/SportEdu/edu3.png",
    images: ["/images/SportEdu/edu1-1.jpg", "/images/SportEdu/edu1-1.jpg"],
    level: "مبتدی",
    equipment: ["دمبل"],
    muscles: {
      primary: ["جلو بازو"],
      secondary: ["ساعد"],
    },
    description:
      "جلو بازو دمبل یکی از بهترین حرکات برای افزایش حجم و فرم‌دهی عضلات بازو است.",
    executionSteps: [
      "دمبل‌ها را در دست بگیر",
      "دست‌ها کنار بدن باشد",
      "دمبل را تا نزدیکی شانه بالا بیاور",
      "آهسته به حالت اول برگرد",
    ],
    tips: ["آرنج‌ها ثابت بمانند", "از تاب دادن بدن خودداری کن"],
    commonMistakes: ["تاب دادن بدن", "سرعت زیاد حرکت"],
    benefits: ["افزایش حجم جلو بازو", "تقویت قدرت دست"],
    relatedExercises: ["hammer-curl", "barbell-curl"],
  },
  {
    id: 4,
    title: "نشر از بغل",
    slug: "lateral-raise",
    image: "/images/SportEdu/edu4.jpg",
    images: ["/images/SportEdu/edu1-1.jpg", "/images/SportEdu/edu1-1.jpg"],
    level: "مبتدی",
    equipment: ["دمبل"],
    muscles: {
      primary: ["سرشانه جانبی"],
      secondary: ["ذوزنقه‌ای"],
    },
    description:
      "نشر از بغل یکی از بهترین حرکات برای پهن‌تر نشان دادن سرشانه‌ها است.",
    executionSteps: [
      "دمبل‌ها کنار بدن",
      "دست‌ها را تا ارتفاع شانه بالا بیاور",
      "به آرامی پایین بیاور",
    ],
    tips: ["وزنه سبک انتخاب کن", "حرکت را کنترل کن"],
    commonMistakes: ["بالا بردن بیش از حد دست‌ها", "تاب دادن بدن"],
    benefits: ["پهن‌تر شدن سرشانه", "افزایش فرم بدنی"],
    relatedExercises: ["front-raise", "shoulder-press"],
  },
  {
    id: 5,
    title: "بارفیکس",
    slug: "pull-up",
    image: "/images/SportEdu/edu5.webp",
    images: ["/images/SportEdu/edu1-1.jpg", "/images/SportEdu/edu1-1.jpg"],
    level: "پیشرفته",
    equipment: ["میله بارفیکس"],
    muscles: {
      primary: ["پشت", "زیر بغل"],
      secondary: ["جلو بازو", "ساعد"],
    },
    description:
      "بارفیکس یکی از سخت‌ترین و مؤثرترین حرکات وزن بدن برای تقویت عضلات پشت است.",
    executionSteps: [
      "از میله آویزان شو",
      "بدن را بالا بکش تا چانه از میله رد شود",
      "آهسته پایین بیا",
    ],
    tips: ["بدن را تاب نده", "کنترل کامل حرکت"],
    commonMistakes: ["تاب خوردن بدن", "حرکت ناقص"],
    benefits: ["افزایش قدرت پشت", "تقویت grip دست"],
    relatedExercises: ["lat-pulldown", "row"],
  },
  {
    id: 6,
    title: "پارالل",
    slug: "dip",
    image: "/images/SportEdu/edu6.jpg",
    images: ["/images/SportEdu/edu1-1.jpg", "/images/SportEdu/edu1-1.jpg"],
    level: "متوسط",
    equipment: ["پارالل"],
    muscles: {
      primary: ["پشت بازو", "سینه"],
      secondary: ["سرشانه"],
    },
    description:
      "حرکت پارالل یکی از بهترین حرکات وزن بدن برای افزایش قدرت پشت بازو و سینه است.",
    executionSteps: [
      "روی پارالل قرار بگیر",
      "بدن را پایین بیاور",
      "با فشار دست‌ها بالا برو",
    ],
    tips: ["بدن صاف بماند", "دامنه کامل حرکت"],
    commonMistakes: ["خم شدن بیش از حد بدن", "دامنه ناقص"],
    benefits: ["افزایش قدرت پشت بازو", "تقویت بالاتنه"],
    relatedExercises: ["push-up", "close-grip-bench-press"],
  },
];
